site_name:  SILK
site_url: https://wicked-wlzard.github.io/slik/
repo_url: https://github.com/wicked-wlzard/silk
repo_name: wicked-wlzard/silk
site_description: An intuitive and efficient game development framework for Roblox that streamlines the process of creating engaging and immersive games.

# Local
# site_url: ""
# use_directory_urls: false

theme:
  name: material
  favicon: assets/diamonds.png
  logo: assets/diamonds.png
  features:
    - content.code.annotate
  palette:
    - scheme: slate
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.inlinehilite