title = 'SILK'

apiCategories = [
    'utility',
]

[docusaurus]
favicon = 'favicon.png'
tagline = 'An intuitive game development framework for Roblox that streamlines the process of creating games quickly'

[home]
enabled = true
includeReadme = true

[[navbar.items]]
href = 'https://github.com/wicked-wlzard/silk/releases'
label = 'Get SILK'

[[classOrder]]
section = 'SILK'
classes = ['Silk', 'Package']

[[classOrder]]
section = 'Essential Packages'
classes = ['Client']