title = 'SILK'

apiCategories = [
    'utility',
]

[docusaurus]
favicon = 'favicon.png'
tagline = 'An intuitive game development framework for Roblox designed to simplify the process of game development'

[home]
enabled = true
# includeReadme = true

[[navbar.items]]
href = 'https://github.com/wicked-wlzard/silk/releases'
label = 'Get SILK'

[[classOrder]]
section = 'SILK'
classes = ['Silk', 'Package']

[[classOrder]]
section = 'Essential Packages'
classes = ['Client']

[[home.features]]
title = 'Consistent'
description = 'Provides a consistent interface between scripts to access shared data or functionality, avoiding duplication of effort and reduce the amount of code needed to accomplish a particular task, ultimately simplifying the overall process of development'

[[home.features]]
title = 'Efficient'
description = 'Ensure effective communication between scripts in a controlled manner by having a centralized point of access for data and functionality, reducing the risk of bugs, conflicts, or other inconsistencies in the codebase'

[[home.features]]
title = 'Modular'
description = 'Simplified game development workflows with better organization and flexibility through a highly modular ecosystem, obtaining the ability to modify different components of the game in a non-destructive manner'