title = 'SILK'

[docusaurus]
favicon = 'favicon.png'
tagline = 'An intuitive game development framework for Roblox that streamlines the process of creating games quickly'

[home]
enabled = true
includeReadme = true