title = 'SILK Game Framework'

apiCategories = [
    'utility',
    'network',
    'initializer',
]

[docusaurus]
favicon = 'favicon.png'
tagline = 'An intuitive game development framework for Roblox designed to streamline the process of game development'

[home]
enabled = true
# includeReadme = true

[[navbar.items]]
href = 'https://github.com/wicked-wlzard/silk/releases'
label = 'Releases'

[[classOrder]]
section = 'SILK'
collapsed = false
classes = ['Silk', 'Package']

[[classOrder]]
section = 'Included Packages'
collapsed = false
classes = ['Client', 'Network']

[[home.features]]
title = 'Consistent'
description = 'Provides a consistent interface between scripts to access shared data or functionality, avoiding duplication of effort and reducing the amount of code needed to accomplish a particular task, ultimately simplifying the overall process of development'

[[home.features]]
title = 'Efficient'
description = 'Ensures effective communication between scripts in a controlled manner by having a centralized point of access for data and functionality, reducing the risk of bugs, conflicts, or other inconsistencies in the codebase'

[[home.features]]
title = 'Modular'
description = 'Simplifies game development workflows with better organization and flexibility through a highly modular ecosystem, giving the ability to modify different components of the project in a non-destructive manner'