name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Build
        run: |
          wget https://github.com/rojo-rbx/rojo/releases/download/v7.2.1/rojo-7.2.1-linux.zip
          unzip rojo-7.2.1-linux.zip
          ./rojo build silk.project.json --output silk.rbxm

      - name: Create Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./silk.rbxm
          asset_name: silk_rbxm
          asset_content_type: application/xml
